### ISSUE TITLE
[Feat]: Landsat Acquisition Tool API

### ISSUE THREAD

**Issue by wikipop** [EKK-Ingarden/LandsatWebTracker#17]
### My suggestion

There is [this thing](https://landsat.usgs.gov/landsat_acq) and it is supposed to tell us when and where landsat will be. Someone must examine how this thing works and implement some util for us to use.

- [x] Examine [Landsat Acquisition tool](https://landsat.usgs.gov/landsat_acq)
- [ ] Create interface for communication in: (lat, lon), out: (datetime)

**Comment by wikipop** [comment]
norbert found [this endpoint](https://landsat.usgs.gov/landsat/all_in_one_pending_acquisition/L9/Pend_Acq/y2024/Sep/Sep-11-2024.txt) probably very useful

**Comment by Norbiros** [comment]
Depends on #31
