### ISSUE TITLE
[Feat]: Site-wide dark theme implementation

### ISSUE THREAD

**Issue by wikipop** [EKK-Ingarden/LandsatWebTracker#28]
### My suggestion

Self explanatory. I would suggest using [This approach](https://www.shadcn-vue.com/docs/dark-mode/nuxt.html) (It SHOULD BE [unocss might be a problem] like 5 min task)

**Comment by Norbiros** [comment]
IMO supporting multiple modes is bad idea in our case. It means we have to spend more time developing and supporting those themes. Also what about for example landing site? How to make it look good with white theme?
![Screenshot from 2024-09-19 19-26-42](https://github.com/user-attachments/assets/99676573-7c30-4510-81ff-a37547c66acd)

**Comment by wikipop** [comment]
Main problem that i have (and forgot to write) is that shadcn components actually might render in light theme (idk on what it depends, probably system setting). I experience this bug in #25, date picker opens in light mode. Alternatively we can just enforce dark mode everywhere.

**Comment by Norbiros** [comment]
> you can put class="dark" in your html tag in app.html

I think the way to go is enforcing dark mode hihi
