### ISSUE TITLE
[Feat]: Design project icon

### ISSUE THREAD

**Issue by Norbiros** [EKK-Ingarden/LandsatWebTracker#7]
### My suggestion

Pretty self explanatory. Design icon used in website, favicon etc.

**Comment by toriishia** [comment]
![logo](https://github.com/user-attachments/assets/4f35ff98-4415-43ed-9c2f-d47d8ec7c45b)
![logo](https://github.com/user-attachments/assets/d520611a-d6f4-4e47-861e-f6e95d0a9e0b)
