### ISSUE TITLE
[Feat]: Map UI component

### ISSUE THREAD

**Issue by wikipop** [EKK-Ingarden/LandsatWebTracker#8]
### Required feature

Map frontend component that returns location in WGS84 system for place chosen by the user.

- [x] map component
- [x] map reactivity
- [x] location search bar

Preferable technologies
- Vue lib based on [OpenStreetMap](https://www.openstreetmap.org/)

**Comment by Norbiros** [comment]
I'll probably use https://nuxt.com/modules/leaflet, okay?
